name: Publish GitHub Pages

on:
  workflow_call:
    inputs:
      destination_dir:
        required: true
        type: string

jobs:
  publish-to-gh-pages:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Ensure `destination_dir` is not empty
        if: ${{ inputs.destination_dir == '' }}
        run: exit 1
      - name: Setup the repository
        uses: metamask/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: true
      - name: Run build script
        run: yarn build:prod
      - name: Deploy to `${{ inputs.destination_dir }}` directory of `gh-pages` branch
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ inputs.destination_dir }}
