name: Publish release candidate to GitHub Pages

on:
  push:
    branches: 'release/**'

jobs:
  get-release-version:
    name: Get release version
    runs-on: ubuntu-24.04
    outputs:
      release-version: ${{ steps.release-name.outputs.RELEASE_VERSION }}
    steps:
      - name: Extract release version from branch name
        id: release-name
        run: |
          BRANCH_NAME='${{ github.ref_name }}'
          echo "RELEASE_VERSION=v${BRANCH_NAME#release/}" >> "$GITHUB_OUTPUT"
  publish-to-gh-pages:
    name: Publish build to `rc-${{ needs.get-release-version.outputs.release-version }}` directory of `gh-pages` branch
    permissions:
      contents: write
    uses: ./.github/workflows/publish-gh-pages.yml
    needs: get-release-version
    with:
      destination_dir: rc-${{ needs.get-release-version.outputs.release-version }}
