name: Publish Release

on:
  workflow_call:

jobs:
  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - uses: MetaMask/action-publish-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.METAMASKBOT_PUBLISH_TOKEN }}
