name: Publish main branch to GitHub Pages

on:
  push:
    branches: main

jobs:
  publish-to-gh-pages:
    name: Publish build to `latest` directory of `gh-pages` branch
    uses: ./.github/workflows/publish-gh-pages.yml
    secrets: inherit
    with:
      destination_dir: latest
